FROM node:alpine3.18 as build

#Declare the build time env variables
ARG NEXT_PUBLIC_SERVER_URL
ARG NEXT_PUBLIC_LIVEBLOCK_API_KEY
ARG OPENAI_API_KEY
ARG EDGE_STORE_ACCESS_KEY
ARG EDGE_STORE_SECRET_KEY
ARG NEXT_PUBLIC_LIVEKIT_URL
ARG LIVEKIT_API_KEY
ARG LIVEKIT_API_SECRET

#Set default values for env
ENV NEXT_PUBLIC_SERVER_URL =$NEXT_PUBLIC_SERVER_URL
ENV NEXT_PUBLIC_LIVEBLOCK_API_KEY =$NEXT_PUBLIC_LIVEBLOCK_API_KEY
ENV OPENAI_API_KEY =$OPENAI_API_KEY
ENV EDGE_STORE_ACCESS_KEY =$EDGE_STORE_ACCESS_KEY
ENV EDGE_STORE_SECRET_KEY =$EDGE_STORE_SECRET_KEY
ENV NEXT_PUBLIC_LIVEKIT_URL =$NEXT_PUBLIC_LIVEKIT_URL
ENV LIVEKIT_API_KEY =$LIVEKIT_API_KEY
ENV LIVEKIT_API_SECRET =$LIVEKIT_API_SECRET

#Build App
WORKDIR /app

COPY package.json .

RUN npm i

COPY . .

RUN npm run build

#Serve nginx

FROM nginx:1.23-alpine
WORKDIR /usr/share/nginx/html
RUN rm -rf *
COPY --from=build /app/.next ./.next

EXPOSE 80
ENTRYPOINT [ "nginx","-g","daemon off;" ]

CMD [ "npm" ,"run","start" ]